# Generated by Django 5.1.6 on 2025-03-01 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публікації'),
        ),
        migrations.AddField(
            model_name='news',
            name='givenFrom',
            field=models.CharField(default='', max_length=160, verbose_name='Звідки взято інформацію / Хто написав'),
        ),
        migrations.AddField(
            model_name='news',
            name='givenFromUrl',
            field=models.SlugField(default='', max_length=160, verbose_name='Посилання на статтю'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='posters_of_news/', verbose_name='Зображення'),
        ),
    ]
