# Generated by Django 5.1.6 on 2025-03-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_news_date_news_givenfrom_news_givenfromurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=150, verbose_name='Короткий опис'),
        ),
    ]
