# Generated by Django 5.1.6 on 2025-03-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_news_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='givenFrom',
            field=models.CharField(default='', max_length=160, verbose_name='Where did the information come from / Who wrote it'),
        ),
        migrations.AlterField(
            model_name='news',
            name='givenFromUrl',
            field=models.SlugField(default='', max_length=160, null=True, verbose_name='Посилання на статтю'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name of article'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=150, verbose_name='Short description'),
        ),
    ]
