# Generated by Django 5.1.6 on 2025-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_alter_news_description_alter_news_givenfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='givenFrom',
            field=models.CharField(default='', max_length=160, verbose_name='Звідки взято інформацію / Хто написав'),
        ),
        migrations.AlterField(
            model_name='news',
            name='givenFromUrl',
            field=models.CharField(blank=True, default='', max_length=160, null=True, verbose_name='Посилання на статтю'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наза статті'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=150, verbose_name='Короткий опис'),
        ),
    ]
