# Generated by Django 5.1.6 on 2025-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_alter_news_description_alter_news_givenfrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Назва товару')),
                ('short_description', models.CharField(default='', max_length=70, verbose_name='Короткий опис')),
                ('description', models.TextField(verbose_name='Опис')),
                ('urls', models.SlugField(max_length=160)),
                ('image', models.ImageField(default='', upload_to='posters_of_news/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Наза статті'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(default='', max_length=70, verbose_name='Короткий опис'),
        ),
    ]
