# Generated by Django 5.1.6 on 2025-03-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_products_alter_news_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveBigIntegerField(default=0, help_text='Вказувати суму в доларах', verbose_name='Ціна'),
        ),
    ]
