# Generated by Django 5.1.6 on 2025-03-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='products/', verbose_name='Зображення'),
        ),
    ]
