# Generated by Django 5.1.6 on 2025-03-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_avaible',
            field=models.BooleanField(default=False, verbose_name='Чи в наявності'),
        ),
    ]
