# Generated by Django 5.1.6 on 2025-03-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_news_is_avaible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_avaible',
        ),
        migrations.AddField(
            model_name='products',
            name='is_avaible',
            field=models.BooleanField(default=False, verbose_name='Чи в наявності'),
        ),
    ]
