# Generated by Django 5.1.6 on 2025-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_remove_news_is_avaible_products_is_avaible'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Наза статті'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_uk',
            field=models.CharField(max_length=70, null=True, verbose_name='Наза статті'),
        ),
    ]
