# Generated by Django 5.1.6 on 2025-03-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0012_news_description_en_news_description_uk_news_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='urls',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='urls',
            new_name='url',
        ),
    ]
