# Generated by Django 5.1.6 on 2025-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_rename_urls_news_url_rename_urls_products_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_uk',
            field=models.CharField(default='', max_length=70, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Назва товару'),
        ),
        migrations.AddField(
            model_name='products',
            name='name_uk',
            field=models.CharField(max_length=70, null=True, verbose_name='Назва товару'),
        ),
    ]
